### PR TITLE
Fix ReadPumpSettings for x22 and older pumps.

### LINKED ISSUE #218: incorrect maxBolus in  ReadSettings response on x22 pumps
While debugging my own code and comparing it to yours, I think I found a bug here:
https://github.com/ps2/rileylink_ios/blob/dev/MinimedKit/Messages/ReadSettingsCarelinkMessageBody.swift#L56

I may be misunderstanding your Swift code, but on a x22 model pump, the maxBolus value is in byte 6, not byte 7.
See https://github.com/bewest/decoding-carelink/blob/master/decocare/commands.py#L1274
versus https://github.com/bewest/decoding-carelink/blob/master/decocare/commands.py#L1310
(Ben's indices are all off by 1 compared to yours (and mine)).

Here is some test data:

model 522 pump

C0 15 0C 02 00 05 01 78 00 64 00 00 01 00 01 00 00 64 01 03 00 0F

should produce (among other values):

```
{
  "AutoOff": "12h0m0s",
  "InsulinAction": "3h0m0s",
  "InsulinConcentration": 100,
  "MaxBolus": 12,
  "MaxBasal": 2.5,
  "RfEnabled": true,
  "TempBasalType": "Absolute",
  "SelectedPattern": 0
}
```

model 523 pump

C0 19 0C 02 00 01 01 00 8C 00 50 00 00 00 00 00 00 64 01 03 00 14 00 64 00 00

```
{
  "AutoOff": "12h0m0s",
  "InsulinAction": "3h0m0s",
  "InsulinConcentration": 100,
  "MaxBolus": 14,
  "MaxBasal": 2,
  "RfEnabled": false,
  "TempBasalType": "Absolute",
  "SelectedPattern": 0
}
```

### PR DESCRIPTION
**Pull request by ps2**
Fixes #218

### CODE REVIEW

File: MinimedKit/Messages/ReadSettingsCarelinkMessageBody.swift [hunk 1]
```diff
@@ -52,11 +52,20 @@ public class ReadSettingsCarelinkMessageBody: CarelinkLongMessageBody {
         guard rxData.count == type(of: self).length else {
             return nil
         }
-
-        let maxBolusTicks: UInt8 = rxData[7]
+        
+        let newer = rxData[7] == 25 // x23
```
Comment (loudnate) [inline MinimedKit/Messages/ReadSettingsCarelinkMessageBody.swift]: Interesting. Does this constant appear in other messages with shifts, like read reservoir volume?

**Review by loudnate — APPROVED** [review]

**Comment by loudnate** [comment]
```
Failing tests:
    -[ReadSettingsCarelinkMessageBodyTests testValidSettings()]
    -[ReadSettingsCarelinkMessageBodyTests testValidSettings()]
```
