### PR TITLE
Fix bolus wizard settings size on older pumps

### LINKED ISSUE #105: UnknownEventType(93) thrown when fetching recent history with "ChangeCarbRatioPattern" event
When fetching recent history from a Medtronic 722, UnknownEventType(93) is thrown if ChangeCarbRatioPattern event is in recent history.

Here are the CSV logs surrounding the problematic event, pulled from carelink:
# 

83 5/29/2016 20:10:57 5/29/2016 20:10 0.925 Rate 0:30:00
ChangeTempBasal RATE=0.925,
DURATION=1800000, ACTION_REQUESTOR=rf_diagnostic 1.71E+10 54770231 312 Paradigm
722

84 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBGTargetRange
PATTERN_DATUM_ID=17077012918,
INDEX=0, AMOUNT_LOW=95, AMOUNT_HIGH=105, START_TIME=0 1.71E+10
54770231 301 Paradigm
722

85 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBolusWizardSetup
NEW_CONFIG_DATUM_ID=17077012929,
OLD_CONFIG_DATUM_ID=17077012920, ACTION_REQUESTOR=pump 1.71E+10
54770231 311 Paradigm
722

86 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBolusWizardSetupConfig
IS_SETUP_COMPLETE=true,
IS_BOLUS_WIZARD_ENABLED=true, CARB_UNITS=grams, BG_UNITS=mg dl,
CARB_RATIO_PATTERN_DATUM_ID=17077012921,
INSULIN_SENSITIVITY_PATTERN_DATUM_ID=17077012923,
BG_TARGET_RANGE_PATTERN_DATUM_ID=17077012927, INSULIN_ACTION_CURVE=240
1.71E+10 54770231 302 Paradigm 722

87 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBGTargetRange
PATTERN_DATUM_ID=17077012927,
INDEX=0, AMOUNT_LOW=95, AMOUNT_HIGH=105, START_TIME=0 1.71E+10
54770231 310 Paradigm
722

88 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBGTargetRangePattern
ORIGINAL_UNITS=mg
dl, SIZE=1 1.71E+10 54770231 309 Paradigm 722

89 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012923,
INDEX=2, AMOUNT=30, START_TIME=81000000 1.71E+10 54770231 308 Paradigm 722

90 5/29/2016 20:16:48 5/29/2016 20:16 ChangeCarbRatioPattern SIZE=1 1.71E+10
54770231 294 Paradigm 722

91 5/29/2016 20:16:48 5/29/2016 20:16 ChangeCarbRatio
PATTERN_DATUM_ID=17077012912,
INDEX=0, AMOUNT=8, UNITS=grams, START_TIME=0 1.71E+10 54770231 295 Paradigm
722

92 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivityPattern
ORIGINAL_UNITS=mg
dl, SIZE=3 1.71E+10 54770231 296 Paradigm 722

93 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012914,
INDEX=0, AMOUNT=30, START_TIME=0 1.71E+10 54770231 297 Paradigm 722

94 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012914,
INDEX=1, AMOUNT=20, START_TIME=36000000 1.71E+10 54770231 298 Paradigm 722

95 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012914,
INDEX=2, AMOUNT=30, START_TIME=59400000 1.71E+10 54770231 299 Paradigm 722

96 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBGTargetRangePattern
ORIGINAL_UNITS=mg
dl, SIZE=1 1.71E+10 54770231 300 Paradigm 722

97 5/29/2016 20:16:48 5/29/2016 20:16 ChangeBolusWizardSetupConfig
IS_SETUP_COMPLETE=true,
IS_BOLUS_WIZARD_ENABLED=true, CARB_UNITS=grams, BG_UNITS=mg dl,
CARB_RATIO_PATTERN_DATUM_ID=17077012912,
INSULIN_SENSITIVITY_PATTERN_DATUM_ID=17077012914,
BG_TARGET_RANGE_PATTERN_DATUM_ID=17077012918, INSULIN_ACTION_CURVE=240
1.71E+10 54770231 293 Paradigm 722

98 5/29/2016 20:16:48 5/29/2016 20:16 ChangeCarbRatioPattern SIZE=1 1.71E+10
54770231 303 Paradigm 722

99 5/29/2016 20:16:48 5/29/2016 20:16 ChangeCarbRatio
PATTERN_DATUM_ID=17077012921,
INDEX=0, AMOUNT=8, UNITS=grams, START_TIME=0 1.71E+10 54770231 304 Paradigm
722

100 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivityPattern
ORIGINAL_UNITS=mg
dl, SIZE=3 1.71E+10 54770231 305 Paradigm 722

101 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012923,
INDEX=0, AMOUNT=30, START_TIME=0 1.71E+10 54770231 306 Paradigm 722

102 5/29/2016 20:16:48 5/29/2016 20:16 ChangeInsulinSensitivity
PATTERN_DATUM_ID=17077012923,
INDEX=1, AMOUNT=20, START_TIME=36000000 1.71E+10 54770231 307 Paradigm 722

103 5/29/2016 20:21:00 5/29/2016 20:21 3.5 Rate 0:30:00
ChangeTempBasal RATE=3.5,
DURATION=1800000, ACTION_REQUESTOR=rf_diagnostic 1.71E+10 54770231 292 Paradigm
722
# 

Here's the dump of the event's page pulled during the crash:
`<5a0f7050 141d1015 13000800 00000000 00000000 00000000 00001e14 14211e00 00000000 00000000 00005f69 00000000 00000000 00000000 00000000 00000000 00151300 08000000 00000000 00000000 00000000 1e14142d 1e000000 00000000 00000000 5f690000 00000000 00000000 00000000 00000000 00000044 338c4055 145d1000 16014055 145d1033 3e445a14 5d100016 01445a14 5d10335a 4464145d 10001601 4464145d 10335e40 69145d10 00160140 69145d10 010a0a00 4a6b341d 10010f0f 00797934 1d10010a 0a00484b 351d1033 83445a15 5d100016 01445a15 5d10333c 4369155d 10001601 4369155d 10011919 006f7a35 1d10333c 4b41165d 10001601 4b41165d 10333c4e 55165d10 0016014e 55165d10 333c486e 165d1000 1601486e 165d1033 1b4c7316 5d100016 014c7316 5d10333c 5f4b175d 10001601 5f4b175d 10010808 00554d37 1d100108 08006a5d 371d1033 3c656417 5d100016 01656417 5d100105 0500766a 371d1033 3c487817 5d100016 01487817 5d100700 000a6a5d 906d5d90 050c00e8 00000000 0a6a0562 34050830 00000508 30000000 00000005 08641300 0000130c 00e80000 0033394a 50005e10 0016014a 50005e10 33394864 005e1000 16014864 005e1033 00496900 5e100016 01496900 5e103300 4878005e 10001601 4878005e 10330041 55015e10 00160141 55015e10 3348495f 015e1000 1601495f 015e1033 39456401 5e100016 01456401 5e103348 4a69015e 10001601 4a69015e 1033104c 73015e10 0016014c 73015e10 33394578 015e1000 16014578 015e1033 39455002 5e100016 01455002 5e103314 465a025e 10001601 465a025e 1033004a 5f025e10 0016014a 5f025e10 3300456e 025e1000 1601456e 025e1033 00424103 5e100016 01424103 5e103300 4550035e 10001601 4550035e 10330049 5f035e10 00160149 5f035e10 3300456e 035e1000 1601456e 035e1033 39467803 5e100016 01467803 5e10338c 4d46045e 10001601 4d46045e 10338c46 64045e10 00160146 64045e10 33444a41 055e1000 16014a41 055e1001 04040075 61281e10 33447968 085e1000 16017968 085e1033 4a797208 5e100016 01797208 5e103344 4478085e 10001601 4478085e 10334442 50095e10 00160142 50095e10 33147954 095e1000 16017954 095e1033 44415a09 5e100016 01415a09 5e10338c 7968095e 10001601 7968095e 10011414 006e6c29 1e103344 7972095e 10001601 7972095e 10335841 460a5e10 00160141 460a5e10 010a0a00 47492a1e 10336841 500a5e10 00160141 500a5e10 010a0a00 6b512a1e 10334441 5a0a5e10 00160141 5a0a5e10 33004150 0b5e1000 16014150 0b5e1033 00455f0b 5e100016 01455f0b 5e103346 416e0b5e 10001601 416e0b5e 10334641 460c5e10 00000000 00005a49>`

### PR DESCRIPTION
**Pull request by ps2**
fixes #105

### CODE REVIEW

File: MinimedKitTests/HistoryPageTests.swift [hunk 1]
```diff
@@ -192,4 +192,32 @@ class HistoryPageTests: XCTestCase {
...
+            timestamp = NSDateComponents(gregorianYear: 2016, month: 5, day: 29, hour: 20, minute: 21, second: 0)
+            
+            XCTAssertEqual(tempBasal.timestamp, timestamp)
+            
+        } catch HistoryPage.Error.InvalidCRC {
+            XCTFail("page decoding threw invalid crc")
+        } catch HistoryPage.Error.UnknownEventType(_) {
+            XCTFail("unknown event type")
+        } catch {
+            NSLog("Unexpected exception...")
```
Comment (loudnate) [inline MinimedKitTests/HistoryPageTests.swift]: XCTFail here too?

**Comment by loudnate** [comment]
LGTM

**Comment by ps2** [comment]
^ Fail tests on _un_expected exception. :)
